Repository Mojacknong/Farmus_App, pull requests merged in 2023-11, with the labels that each got.

#17 [Feat] : 온보딩 레이아웃 구현
  assets/image/ic_onboarding_profile.svg
  lib/common/farmus_theme_data.dart
  lib/common/primary_button.dart
  lib/main.dart
  lib/res/images/image_asset.dart
  lib/view/main/main_screen.dart
  lib/view/onboarding/component/next_button.dart
  lib/view/onboarding/component/onboarding_finish.dart
  lib/view/onboarding/component/onboarding_first.dart
  lib/view/onboarding/component/onboarding_fourth.dart
  lib/view/onboarding/component/onboarding_second.dart
  lib/view/onboarding/component/onboarding_third.dart
  lib/view/onboarding/component/previous_button.dart
  lib/view/onboarding/component/progress_bar.dart
  lib/view/onboarding/component/select_box.dart
  lib/view/onboarding/onboarding_screen.dart
  lib/view_model/onboarding_controller.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 아린 🌾

#18 [Feat] : 온보딩 레이아웃 버튼 활성화 / 비활성화 구현
  lib/main.dart
  lib/view/main/main_screen.dart
  lib/view/onboarding/component/next_button.dart
  lib/view/onboarding/component/onboarding_first.dart
  lib/view/onboarding/component/onboarding_fourth.dart
  lib/view/onboarding/component/onboarding_second.dart
  lib/view/onboarding/component/onboarding_third.dart
  lib/view/onboarding/component/previous_button.dart
  lib/view/onboarding/component/progress_bar.dart
  lib/view/onboarding/component/select_box.dart
  lib/view/onboarding/onboarding_screen.dart
  lib/view_model/onboarding_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#19 [Feat] : 온보딩 최종 레이아웃 구현
  assets/image/logo_onboarding.svg
  ios/Podfile.lock
  lib/common/bouncing.dart
  lib/common/farmus_theme_data.dart
  lib/common/primary_button.dart
  lib/view/login/login_screen.dart
  lib/view/main/main_screen.dart
  lib/view/onboarding/component/next_button.dart
  lib/view/onboarding/component/onboarding_finish.dart
  lib/view/onboarding/component/onboarding_fourth.dart
  lib/view/onboarding/component/previous_button.dart
  lib/view/onboarding/component/progress_bar.dart
  lib/view/onboarding/component/select_box.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#22 [Feat] : 커뮤니티 메인 페이지 레이아웃 구현
  assets/font/Pretendard-Black.ttf
  assets/font/Pretendard-Bold.ttf
  assets/font/Pretendard-Extra-Bold.ttf
  assets/font/Pretendard-Extra-Light.ttf
  assets/font/Pretendard-Light.ttf
  assets/font/Pretendard-Medium.ttf
  assets/font/Pretendard-Regular.ttf
  assets/font/Pretendard-Semi-Bold.ttf
  assets/font/Pretendard-Thin.ttf
  assets/image/ic_arrow_right.svg
  assets/image/ic_edit.svg
  assets/image/ic_profile.svg
  assets/image/image_example_community.png
  assets/image/image_example_community2.png
  assets/image/image_example_profile.png
  assets/image/image_example_profile2.png
  lib/common/custom_app_bar.dart
  lib/common/farmus_theme_data.dart
  lib/main.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/button_next_my_post.dart
  lib/view/community/component/community_category.dart
  lib/view/community/component/community_content.dart
  lib/view/community/component/community_feed.dart
  lib/view/community/component/community_picture.dart
  lib/view/community/component/community_profile.dart
  lib/view/community/component/floating_button_post.dart
  lib/view/community/component/my_post_profile.dart
  lib/view/community/component/post_category.dart
  lib/view/community/my_post/my_post_screen.dart
  lib/view/example/components/app_bar.dart
  lib/view/example/example_screen.dart
  lib/view/login/login_screen.dart
  lib/view/onboarding/component/next_button.dart
  lib/view/onboarding/component/onboarding_first.dart
  lib/view/onboarding/component/onboarding_fourth.dart
  lib/view/onboarding/component/onboarding_second.dart
  lib/view/onboarding/component/onboarding_third.dart
  lib/view/onboarding/component/progress_bar.dart
  lib/view/onboarding/component/select_box.dart
  lib/view/onboarding/onboarding_screen.dart
  lib/view_model/controllers/community_feed_controller.dart
  lib/view_model/controllers/onboarding_controller.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 아린 🌾

#23 [Feat] : 커뮤니티 상세 글 페이지 레이아웃 구현
  assets/image/ic_arrow_left.svg
  assets/image/ic_arrow_up.svg
  assets/image/ic_more_vertical.svg
  lib/common/custom_app_bar.dart
  lib/common/farmus_theme_data.dart
  lib/common/primary_app_bar.dart
  lib/common/primary_bottom_sheet.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/bottom_comment.dart
  lib/view/community/component/community_category.dart
  lib/view/community/component/community_comment.dart
  lib/view/community/component/community_comment_count.dart
  lib/view/community/component/community_content.dart
  lib/view/community/component/community_feed.dart
  lib/view/community/component/community_profile.dart
  lib/view/community/component/detail_post_profile.dart
  lib/view/community/component/floating_button_post.dart
  lib/view/community/component/my_post_profile.dart
  lib/view/community/detail/detail_post_screen.dart
  lib/view/community/post/post_screen.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
  lib/view_model/controllers/community_detail_controller.dart
  lib/view_model/controllers/community_feed_controller.dart
  lib/view_model/controllers/community_post_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#26 [Feat] : 로그인, 온보딩 UI 수정 및 API 연동
  assets/image/google_login.svg
  assets/image/kakao_login.svg
  assets/image/logo_onboarding.svg
  assets/image/logo_tree.svg
  lib/common/primary_button.dart
  lib/data/network/base_api_services.dart
  lib/data/network/login_api_service.dart
  lib/data/network/onboarding_api_service.dart
  lib/main.dart
  lib/repository/login_repository.dart
  lib/repository/onboarding_repository.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/community_category.dart
  lib/view/community/post/post_screen.dart
  lib/view/login/login_screen.dart
  lib/view/onboarding/component/next_button.dart
  lib/view/onboarding/component/onboarding_finish.dart
  lib/view/onboarding/component/onboarding_first.dart
  lib/view/onboarding/component/onboarding_fourth.dart
  lib/view/onboarding/component/onboarding_second.dart
  lib/view/onboarding/component/onboarding_third.dart
  lib/view/onboarding/component/previous_button.dart
  lib/view/onboarding/onboarding_screen.dart
  lib/view_model/controllers/community_feed_controller.dart
  lib/view_model/controllers/community_post_controller.dart
  lib/view_model/controllers/onboarding_controller.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 아린 🌾

#28 [Feat] : 커뮤니티 API 틀 구축 및 로그인 API 데이터 모델 생성하여 리팩토링
  .vscode/settings.json
  lib/data/network/community_api_service.dart
  lib/data/network/login_api_service.dart
  lib/data/network/onboarding_api_service.dart
  lib/model/community_posting.dart
  lib/model/data_model.dart
  lib/model/farmus_user.dart
  lib/repository/community_repository.dart
  lib/repository/login_repository.dart
  lib/repository/onboarding_repository.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/button_next_my_post.dart
  lib/view/community/component/category_list.dart
  lib/view/community/component/community_category.dart
  lib/view/community/component/community_feed.dart
  lib/view/community/component/community_picture.dart
  lib/view/community/component/community_profile.dart
  lib/view/community/component/my_post_feed.dart
  lib/view/community/my_post/my_post_screen.dart
  lib/view/community/post/post_screen.dart
  lib/view/login/login_screen.dart
  lib/view/onboarding/component/onboarding_first.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, refactor 🥔, 아린 🌾

#29 [Feat] : 마이페이지 레이아웃 구현 중 (API 연동 전)
  .vscode/launch.json
  assets/image/arrow_right_mypage.svg
  assets/image/arrow_right_mypage_small.svg
  assets/image/logo_tree.svg
  assets/image/profile_example_mypage.svg
  assets/image/settings_icon.svg
  lib/view/my_page/component/my_challenge_header.dart
  lib/view/my_page/component/my_history_header.dart
  lib/view/my_page/component/my_page_bar.dart
  lib/view/my_page/component/my_page_header.dart
  lib/view/my_page/component/my_page_history.dart
  lib/view/my_page/component/my_page_profile.dart
  lib/view/my_page/history/my_farm_history.dart
  lib/view/my_page/history/my_vege_history.dart
  lib/view/my_page/my_page_screen.dart
Labels: feat 👩🏻‍🌾

#30 [Fix] : 프로필 이미지 연동 에러 수정
  .vscode/launch.json
  .vscode/settings.json
  assets/image/arrow_right_mypage.svg
  assets/image/arrow_right_mypage_small.svg
  assets/image/profile_example_mypage.svg
  assets/image/settings_icon.svg
  lib/data/network/community_api_service.dart
  lib/data/network/login_api_service.dart
  lib/data/network/onboarding_api_service.dart
  lib/model/community_posting.dart
  lib/model/data_model.dart
  lib/model/farmus_user.dart
  lib/repository/community_repository.dart
  lib/repository/login_repository.dart
  lib/repository/onboarding_repository.dart
  lib/res/app_url/app_url.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/button_next_my_post.dart
  lib/view/community/component/category_list.dart
  lib/view/community/component/community_category.dart
  lib/view/community/component/community_feed.dart
  lib/view/community/component/community_picture.dart
  lib/view/community/component/community_profile.dart
  lib/view/community/component/my_post_feed.dart
  lib/view/community/my_post/my_post_screen.dart
  lib/view/community/post/post_screen.dart
  lib/view/login/login_screen.dart
  lib/view/my_page/component/my_challenge_header.dart
  lib/view/my_page/component/my_history_header.dart
  lib/view/my_page/component/my_page_bar.dart
  lib/view/my_page/component/my_page_header.dart
  lib/view/my_page/component/my_page_history.dart
  lib/view/my_page/component/my_page_profile.dart
  lib/view/my_page/history/my_farm_history.dart
  lib/view/my_page/history/my_vege_history.dart
  lib/view/my_page/my_page_screen.dart
  lib/view/onboarding/component/onboarding_first.dart
  pubspec.lock
Labels: hotfix 🫐, 아린 🌾

#33 [Feat] : 커뮤니티 API 연동
  android/app/src/main/AndroidManifest.xml
  lib/data/network/base_api_services.dart
  lib/data/network/community_api_service.dart
  lib/data/network/login_api_service.dart
  lib/data/network/mypage_api_service.dart
  lib/model/community_detail.dart
  lib/model/farmus_user.dart
  lib/model/posting.dart
  lib/model/posting_comment.dart
  lib/model/whole_posting.dart
  lib/repository/community_repository.dart
  lib/repository/mypage_repository.dart
  lib/res/app_url/app_url.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/bottom_comment.dart
  lib/view/community/component/community_comment.dart
  lib/view/community/component/community_feed.dart
  lib/view/community/component/community_picture.dart
  lib/view/community/component/community_profile.dart
  lib/view/community/component/detail_post_profile.dart
  lib/view/community/component/floating_button_post.dart
  lib/view/community/component/my_post_feed.dart
  lib/view/community/detail/detail_post_screen.dart
  lib/view/community/my_post/my_post_screen.dart
  lib/view/community/post/post_screen.dart
  lib/view/my_page/component/my_page_header.dart
  lib/view/my_page/my_page_screen.dart
  lib/view_model/controllers/community_detail_controller.dart
  lib/view_model/controllers/community_feed_controller.dart
  lib/view_model/controllers/community_post_controller.dart
  lib/view_model/controllers/example_controller.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#36 [Feat] : 팜클럽 초기 화면, 탐색 화면 구현
  assets/image/ic_init_farmclub.svg
  assets/image/ic_plus.svg
  assets/image/ic_search.svg
  assets/image/ic_search_small.svg
  assets/image/image_farmclub_blue.png
  assets/image/image_farmclub_green.png
  assets/image/image_farmclub_purple.png
  assets/image/line_vertical_grey1.svg
  lib/common/farmus_theme_data.dart
  lib/common/primary_app_bar.dart
  lib/main.dart
  lib/view/challenge/challenge_screen.dart
  lib/view/farmclub/component/brown_button.dart
  lib/view/farmclub/component/brown_category.dart
  lib/view/farmclub/component/button_to_search.dart
  lib/view/farmclub/component/farmclub.dart
  lib/view/farmclub/component/farmclub_init.dart
  lib/view/farmclub/component/farmclub_text_info.dart
  lib/view/farmclub/component/floating_button_farmclub.dart
  lib/view/farmclub/component/green_button.dart
  lib/view/farmclub/component/recommend_farmclub_list.dart
  lib/view/farmclub/component/recommned_farmclub.dart
  lib/view/farmclub/farmclub_ explore_screen.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/farmclub/farmclub_search_screen.dart
  lib/view/main/main_screen.dart
  lib/view/onboarding/component/onboarding_first.dart
  lib/view_model/user_view_model.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#39 [Feat] : 작물 등록 첫 페이지 및 미션/루틴
  assets/image/basil.svg
  assets/image/bigbox.svg
  assets/image/darkwave.svg
  assets/image/greenonion.svg
  assets/image/greenwave.svg
  assets/image/ic_alarm.svg
  assets/image/ic_plus.svg
  assets/image/lettuce.svg
  assets/image/lettuce1.svg
  assets/image/mission_step.svg
  assets/image/my_history_header.dart
  assets/image/pepper.svg
  assets/image/smallbox.svg
  assets/image/vege_regi_btn.svg
  lib/data/network/home_screen_api_service.dart
  lib/main.dart
  lib/repository/homescreen_repository.dart
  lib/view/home/component/home_custom_app_bar.dart
  lib/view/home/component/home_divider.dart
  lib/view/home/component/home_farmclub.dart
  lib/view/home/component/home_green_box.dart
  lib/view/home/component/home_green_box_user.dart
  lib/view/home/component/home_green_box_user2.dart
  lib/view/home/component/home_routine_list.dart
  lib/view/home/controller/home_club_list_item.dart
  lib/view/home/controller/home_content.dart
  lib/view/home/controller/home_swipe.dart
  lib/view/home/detail/checkboxitem.dart
  lib/view/home/detail/checkboxlist.dart
  lib/view/home/get/home_farm_mission.dart
  lib/view/home/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾

#43 [Feat] : 팜클럽 초기화면 / 팜클럽 탐색 레이아웃 구현
  .vscode/settings.json
  assets/image/ic_like_false.svg
  assets/image/ic_like_true.svg
  assets/image/image_challenge1.png
  assets/image/image_challenge2.png
  lib/common/farmus_theme_data.dart
  lib/view/farmclub/component/button_brown.dart
  lib/view/farmclub/component/button_white.dart
  lib/view/farmclub/component/challenge/challenge_feed.dart
  lib/view/farmclub/component/challenge/challenge_title.dart
  lib/view/farmclub/component/farmclub_init.dart
  lib/view/farmclub/component/farmclub_title_with_divider.dart
  lib/view/farmclub/component/group/group_rate.dart
  lib/view/farmclub/component/group/group_rate_step_false.dart
  lib/view/farmclub/component/group/group_rate_step_true.dart
  lib/view/farmclub/component/record/record_picture.dart
  lib/view/farmclub/component/record/record_profile.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/main/main_screen.dart
  lib/view_model/controllers/farmclub_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#45 [Feat] : 작물 등록/달력 레이아웃 구현
  assets/image/basil_black.svg
  assets/image/basil_col.svg
  assets/image/gray_box.svg
  assets/image/greenonion_black.svg
  assets/image/greenonion_col.svg
  assets/image/ic_check.svg
  assets/image/ic_math-plus.svg
  assets/image/lettuce_black.svg
  assets/image/lettuce_col.svg
  assets/image/pepper_black.svg
  assets/image/pepper_col.svg
  assets/image/selected_box.svg
  assets/image/sesame_black.svg
  assets/image/sesame_col.svg
  assets/image/tomato_black.svg
  assets/image/tomato_col.svg
  lib/view/home/component/home_custom_app_bar.dart
  lib/view/home/component/home_register.dart
  lib/view/home/component/register/customs/calender.dart
  lib/view/home/component/register/customs/dialog.dart
  lib/view/home/component/register/customs/register_app_bar.dart
  lib/view/home/component/register/customs/register_button.dart
  lib/view/home/component/register/customs/select_image_widget.dart
  lib/view/home/component/register/nickname_vege.dart
  lib/view/home/component/register/register_screen.dart
  lib/view/home/component/register/select_vege.dart
  lib/view/home/controller/submit_vege.dart
  lib/view/home/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 건희 🍎

#46 [Feat] : 팜클럽 둘러보기 화면 구현
  assets/image/ic_check_false.svg
  assets/image/ic_check_true.svg
  assets/image/ic_join_check.svg
  assets/image/ic_lettuce_blue.svg
  assets/image/ic_lock.svg
  lib/common/bottom_sheet/bottom_sheet_farmclub_join.dart
  lib/common/bouncing.dart
  lib/common/dialog/Dialog_join_farmclub.dart
  lib/common/farmus_theme_data.dart
  lib/view/community/component/community_comment.dart
  lib/view/farmclub/component/around/farmclub_around_record.dart
  lib/view/farmclub/component/around/farmclub_around_title.dart
  lib/view/farmclub/component/around/farmclub_around_vegetable.dart
  lib/view/farmclub/component/around/vegetable_list.dart
  lib/view/farmclub/component/button_brown.dart
  lib/view/farmclub/component/explore/recommned_farmclub.dart
  lib/view/farmclub/component/farmclub.dart
  lib/view/farmclub/component/farmclub_content.dart
  lib/view/farmclub/component/farmclub_init.dart
  lib/view/farmclub/component/farmclub_title.dart
  lib/view/farmclub/farmclub_detail_screen.dart
  lib/view/farmclub/farmclub_explore_screen.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
  lib/view_model/controllers/farmclub_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#49 [Feat] : 채소 등록 레이아웃 수정
  lib/main.dart
  lib/view/home/component/register/customs/Dialog_register_vege.dart
  lib/view/home/component/register/customs/dialog.dart
  lib/view/home/component/register/customs/select_image_widget.dart
  lib/view/home/component/register/register_screen.dart
  lib/view/home/component/register/select_vege.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#51 [Feat] : 팜클럽 함께 도전해요 / 함께 기록해요 / 내 미션 피드 화면 구현
  lib/view/farmclub/component/button_brown.dart
  lib/view/farmclub/component/button_white.dart
  lib/view/farmclub/component/challenge/challenge_help.dart
  lib/view/farmclub/component/challenge/challenge_step.dart
  lib/view/farmclub/component/challenge/challenge_title.dart
  lib/view/farmclub/component/record/record_picture.dart
  lib/view/farmclub/farmclub_challenge_screen.dart
  lib/view/farmclub/farmclub_detail_screen.dart
  lib/view/farmclub/farmclub_record_screen.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/farmclub/my_farmclub_mission_screen.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#57 [Feat] : 오늘의 루틴 체크박스/바텀시트 적용(UI변경 필요)
  lib/common/bottom_sheet/bottom_sheet_farmclub_join.dart
  lib/view/home/component/home_green_box.dart
  lib/view/home/component/home_routine_list.dart
  lib/view/home/detail/checkboxitem.dart
  lib/view/home/detail/checkboxlist.dart
  lib/view/home/detail/today_routine_list.dart
  lib/view/home/home_screen.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#60 [Feat] : 팜클럽 개설하기 화면, 마이페이지 로그아웃 화면 구현
  lib/common/bottom_sheet/bottom_sheet_farmclub_join.dart
  lib/common/bottom_sheet/cupertino_action_sheet_helper.dart
  lib/main.dart
  lib/view/farmclub/component/around/vegetable_list.dart
  lib/view/farmclub/component/explore/green_button.dart
  lib/view/farmclub/component/farmclub.dart
  lib/view/farmclub/component/farmclub_make_content.dart
  lib/view/farmclub/component/farmclub_make_edit.dart
  lib/view/farmclub/component/farmclub_make_member.dart
  lib/view/farmclub/component/floating_button_farmclub.dart
  lib/view/farmclub/component/my_farmclub.dart
  lib/view/farmclub/component/new_vegetable_item.dart
  lib/view/farmclub/component/new_vegetable_select.dart
  lib/view/farmclub/component/search/brown_category.dart
  lib/view/farmclub/component/search/search_category.dart
  lib/view/farmclub/farmclub_make_screen.dart
  lib/view/my_page/component/my_page_header.dart
  lib/view/my_page/component/my_page_setting_text.dart
  lib/view/my_page/my_page_screen.dart
  lib/view/my_page/my_page_setting_screen.dart
  lib/view/onboarding/component/nickname_field.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
  lib/view_model/controllers/farmclub_controller.dart
  lib/view_model/controllers/farmclub_make_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#61 [Feat] : 마이페이지 수정 및 화면 추가
  lib/common/bottom_sheet/cupertino_action_sheet_helper.dart
  lib/common/farmus_theme_data.dart
  lib/view/community/detail/detail_post_screen.dart
  lib/view/farmclub/farmclub_make_screen.dart
  lib/view/my_page/component/diary_picture.dart
  lib/view/my_page/component/grow_picture.dart
  lib/view/my_page/component/my_history_header.dart
  lib/view/my_page/component/my_page_history.dart
  lib/view/my_page/component/my_page_profile.dart
  lib/view/my_page/history/my_farm_history.dart
  lib/view/my_page/history/my_page_farm_history.dart
  lib/view/my_page/history/my_page_vege_history.dart
  lib/view/my_page/history/my_vege_history.dart
  lib/view/my_page/history_farm_screen.dart
  lib/view/my_page/history_vege_screen.dart
  lib/view/my_page/my_page_screen.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
  lib/view_model/controllers/my_page_profile_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#62 [Hoxfix] : 팜클럽 히스토리 페이지 삭제 및 경로 수정 (#56)
  lib/view/farmclub/component/challenge/challenge_feed.dart
  lib/view/farmclub/farmclub_challenge_screen.dart
  lib/view/my_page/history/my_page_farm_history.dart
  lib/view/my_page/history_farm_screen.dart
  lib/view/my_page/history_vege_screen.dart
Labels: hotfix 🫐, 아린 🌾

#71 [Feat] : 마이페이지 UI 최종 구현
  lib/common/bottom_sheet/cupertino_action_sheet_helper.dart
  lib/view/farmclub/component/group/group_rate.dart
  lib/view/farmclub/component/group/group_rate_step_false.dart
  lib/view/farmclub/component/group/group_rate_step_true.dart
  lib/view/farmclub/component/my_farmclub.dart
  lib/view/farmclub/component/my_farmclub_list.dart
  lib/view/farmclub/my_farmclub_mission_screen.dart
  lib/view/my_page/component/my_page_header.dart
  lib/view/my_page/component/my_page_history.dart
  lib/view/my_page/history/my_page_farm_history.dart
  lib/view/my_page/history_vege_screen.dart
  lib/view/my_page/my_page_setting_screen.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#73 [Feat] : 커뮤니티 UI 변경
  lib/model/community_detail.dart
  lib/view/community/community_screen.dart
  lib/view/community/component/bottom_comment.dart
  lib/view/community/component/button_next_my_post.dart
  lib/view/community/component/community_category.dart
  lib/view/community/component/community_comment.dart
  lib/view/community/component/community_feed.dart
  lib/view/community/component/community_profile.dart
  lib/view/community/component/detail_post_profile.dart
  lib/view/community/component/my_post_feed.dart
  lib/view/community/detail/detail_post_screen.dart
  lib/view/community/my_post/my_post_screen.dart
  lib/view/farmclub/component/search/brown_category.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/onboarding/component/onboarding_fourth.dart
  lib/view/onboarding/component/onboarding_second.dart
  lib/view/onboarding/component/onboarding_third.dart
  lib/view/onboarding/component/select_box.dart
  lib/view/onboarding/onboarding_screen.dart
  lib/view_model/controllers/community_feed_controller.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#78 [Feat] : 채소 난이도 별 페이지 레이아웃 구현/ 홈 페이지 레이아웃 수정
  lib/view/home/component/home_data_loaded.dart
  lib/view/home/component/home_farmclub.dart
  lib/view/home/component/home_green_box_user.dart
  lib/view/home/component/home_green_box_user2.dart
  lib/view/home/component/mission_routine/mission_routine_screen.dart
  lib/view/home/component/register/register_screen.dart
  lib/view/home/detail/home_club_list_item.dart
  lib/view/home/detail/home_content.dart
  lib/view/home/detail/home_custom_app_bar.dart
  lib/view/home/detail/home_divider.dart
  lib/view/home/detail/home_swipe.dart
  lib/view/home/home_difficulty/home_vege_difficult.dart
  lib/view/home/home_difficulty/home_vege_easy.dart
  lib/view/home/home_difficulty/home_vege_normal.dart
  lib/view/home/home_screen.dart
  lib/view/home/home_with_data.dart
  lib/view/home/home_without_vege.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#79 [Feat] : 팜클럽 목록 검색 / 정보 조회 API 연동
  lib/common/bottom_sheet/bottom_sheet_farmclub_exit.dart
  lib/common/bottom_sheet/bottom_sheet_farmclub_join.dart
  lib/data/network/farmclub_api_service.dart
  lib/main.dart
  lib/model/farmclub_detail.dart
  lib/model/farmclub_info_model.dart
  lib/repository/farmclub_repository.dart
  lib/view/farmclub/component/around/farmclub_around_vegetable.dart
  lib/view/farmclub/component/around/vegetable_list.dart
  lib/view/farmclub/component/explore/recommend_farmclub_list.dart
  lib/view/farmclub/component/explore/recommned_farmclub.dart
  lib/view/farmclub/component/farmclub.dart
  lib/view/farmclub/component/farmclub_make_content.dart
  lib/view/farmclub/component/farmclub_make_edit.dart
  lib/view/farmclub/component/farmclub_make_member.dart
  lib/view/farmclub/component/farmclub_text_info.dart
  lib/view/farmclub/component/my_farmclub_info.dart
  lib/view/farmclub/component/new_vegetable_select.dart
  lib/view/farmclub/component/record/record_picture.dart
  lib/view/farmclub/component/search/brown_category.dart
  lib/view/farmclub/component/search/search_category.dart
  lib/view/farmclub/component/search/search_edit.dart
  lib/view/farmclub/farmclub_auth_screen.dart
  lib/view/farmclub/farmclub_challenge_screen.dart
  lib/view/farmclub/farmclub_detail_screen.dart
  lib/view/farmclub/farmclub_explore_screen.dart
  lib/view/farmclub/farmclub_make_screen.dart
  lib/view/farmclub/farmclub_record_screen.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/farmclub/farmclub_search_screen.dart
  lib/view/farmclub/my_farmclub_mission_screen.dart
  lib/view/home/component/home_green_box_user.dart
  lib/view/home/component/mission_routine/combined_widget.dart
  lib/view/home/component/mission_routine/display_text_widget.dart
  lib/view/home/component/register/customs/calender.dart
  lib/view/home/component/register/nickname_vege.dart
  lib/view/home/component/register/register_screen.dart
  lib/view/home/detail/home_content.dart
  lib/view/home/detail/home_custom_app_bar.dart
  lib/view/home/detail/today_routine_list.dart
  lib/view/home/home_screen.dart
  lib/view/home/home_with_data.dart
  lib/view_model/controllers/farmclub/farmclub_controller.dart
  lib/view_model/controllers/farmclub/farmclub_detail_controller.dart
  lib/view_model/controllers/farmclub/farmclub_make_controller.dart
  lib/view_model/controllers/farmclub/farmclub_search_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#82 [Feat] : 앱 바 수정 및 팜클럽 완료 바텀시트 구현
  assets/image/final_background.png
  assets/image/maskgroup.svg
  assets/image/maskgroup2.png
  assets/image/partycorn.svg
  assets/image/svg_final.svg
  lib/main.dart
  lib/view/farmclub/BottomSheetFinal/farm_clear_buttton.dart
  lib/view/farmclub/BottomSheetFinal/farmclub_finish_bottom_sheet.dart
  lib/view/farmclub/BottomSheetFinal/test.dart
  lib/view/home/component/diary/diary_app_bar.dart
  lib/view/home/component/diary/diary_screen.dart
  lib/view/home/component/diary/edit_vege_app_bar.dart
  lib/view/home/component/diary/edit_vege_info.dart
  lib/view/home/component/register/customs/register_app_bar.dart
  lib/view/home/detail/home_custom_app_bar.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#84 [Feat] : 내 팜클럽 조회, 미션 게시글 생성 API 연동
  lib/common/bottom_sheet/bottom_sheet_farmclub_exit.dart
  lib/common/bottom_sheet/bottom_sheet_farmclub_join.dart
  lib/common/dialog/dialog_join_farmclub.dart
  lib/common/farmus_theme_data.dart
  lib/data/network/farmclub_api_service.dart
  lib/model/farmclub_mine.dart
  lib/model/farmclub_mine_detail.dart
  lib/model/farmclub_mission_response.dart
  lib/repository/farmclub_repository.dart
  lib/view/farmclub/BottomSheetFinal/farmclub_finish_bottom_sheet.dart
  lib/view/farmclub/BottomSheetFinal/test.dart
  lib/view/farmclub/component/around/vegetable_list.dart
  lib/view/farmclub/component/challenge/challenge_feed.dart
  lib/view/farmclub/component/challenge/challenge_init.dart
  lib/view/farmclub/component/challenge/challenge_picture.dart
  lib/view/farmclub/component/farmclub.dart
  lib/view/farmclub/component/farmclub_make_edit.dart
  lib/view/farmclub/component/farmclub_make_member.dart
  lib/view/farmclub/component/farmclub_text_info.dart
  lib/view/farmclub/component/farmclub_title.dart
  lib/view/farmclub/component/floating_button_farmclub.dart
  lib/view/farmclub/component/group/group_rate.dart
  lib/view/farmclub/component/my_farmclub.dart
  lib/view/farmclub/component/my_farmclub_list.dart
  lib/view/farmclub/component/new_vegetable_select.dart
  lib/view/farmclub/component/record/record_feed.dart
  lib/view/farmclub/component/record/record_init.dart
  lib/view/farmclub/component/record/record_picture.dart
  lib/view/farmclub/component/search/brown_category.dart
  lib/view/farmclub/component/search/search_category.dart
  lib/view/farmclub/farmclub_auth_screen.dart
  lib/view/farmclub/farmclub_challenge_screen.dart
  lib/view/farmclub/farmclub_detail_screen.dart
  lib/view/farmclub/farmclub_explore_screen.dart
  lib/view/farmclub/farmclub_make_screen.dart
  lib/view/farmclub/farmclub_mission_feed_screen.dart
  lib/view/farmclub/farmclub_record_screen.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/farmclub/farmclub_search_screen.dart
  lib/view/farmclub/my_farmclub_mission_screen.dart
  lib/view/home/component/mission_routine/combined_widget.dart
  lib/view/home/component/mission_routine/display_text_widget.dart
  lib/view/home/component/register/controller/buttom_sheet_home.dart
  lib/view/home/detail/today_routine_list.dart
  lib/view/home/home_screen.dart
  lib/view_model/controllers/bottom_sheet_controller.dart
  lib/view_model/controllers/farmclub/farmclub_auth_controller.dart
  lib/view_model/controllers/farmclub/farmclub_controller.dart
  lib/view_model/controllers/farmclub/farmclub_etc_controller.dart
  lib/view_model/controllers/farmclub/farmclub_explore_controller.dart
  lib/view_model/controllers/farmclub/farmclub_join_controller.dart
  lib/view_model/controllers/farmclub/farmclub_make_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#91 [Feat] : 오늘의 루틴 수정
  lib/view/home/component/mission_routine/calendar_controller.dart
  lib/view/home/component/mission_routine/rotine_api_service.dart
  lib/view/home/component/mission_routine/routine_controller.dart
  lib/view/home/component/mission_routine/routine_data.dart
  lib/view/home/detail/home_custom_app_bar.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#89 [Feat] : 추천 팜클럽 , 팜클럽 미션/일기 목록 조회 API 연동
  lib/common/dialog/dialog_join_farmclub.dart
  lib/data/network/farmclub_api_service.dart
  lib/data/network/mypage_api_service.dart
  lib/data/network/onboarding_api_service.dart
  lib/model/farmclub_detail.dart
  lib/model/farmclub_diary.dart
  lib/model/farmclub_mine_detail.dart
  lib/model/farmclub_mission.dart
  lib/repository/farmclub_repository.dart
  lib/repository/onboarding_repository.dart
  lib/view/farmclub/component/challenge/challenge_feed.dart
  lib/view/farmclub/component/challenge/challenge_picture.dart
  lib/view/farmclub/component/challenge/challenge_step.dart
  lib/view/farmclub/component/explore/recommend_farmclub_list.dart
  lib/view/farmclub/component/explore/recommned_farmclub.dart
  lib/view/farmclub/component/mission_feed.dart
  lib/view/farmclub/component/record/record_feed.dart
  lib/view/farmclub/component/record/record_picture.dart
  lib/view/farmclub/component/record/record_profile.dart
  lib/view/farmclub/farmclub_auth_screen.dart
  lib/view/farmclub/farmclub_challenge_screen.dart
  lib/view/farmclub/farmclub_detail_screen.dart
  lib/view/farmclub/farmclub_explore_screen.dart
  lib/view/farmclub/farmclub_mission_feed_screen.dart
  lib/view/farmclub/farmclub_mission_screen.dart
  lib/view/farmclub/farmclub_record_screen.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/home/home_screen.dart
  lib/view/main/main_screen.dart
  lib/view/my_page/component/my_page_history.dart
  lib/view/my_page/component/my_page_profile.dart
  lib/view_model/controllers/farmclub/farmclub_auth_controller.dart
  lib/view_model/controllers/farmclub/farmclub_controller.dart
  lib/view_model/controllers/farmclub/farmclub_diary_controller.dart
  lib/view_model/controllers/farmclub/farmclub_explore_controller.dart
  lib/view_model/controllers/farmclub/farmclub_mission_controller.dart
  lib/view_model/controllers/my_page_profile_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#103 [Feat] : 채소별 모든 Step 상태 / 전체 가이드라인 연동
  lib/common/bottom_sheet/bottom_sheet_farmclub_join.dart
  lib/data/network/crop_api_service.dart
  lib/data/network/farmclub_api_service.dart
  lib/model/all_vege_infor_dto.dart
  lib/model/crop/crop_info_step.dart
  lib/model/crop/whole_hint.dart
  lib/model/farmclub_detail.dart
  lib/repository/crop_repository.dart
  lib/view/farmclub/component/around/vegetable_list.dart
  lib/view/farmclub/component/challenge/challenge_feed.dart
  lib/view/farmclub/component/challenge/challenge_help.dart
  lib/view/farmclub/component/farmclub_help.dart
  lib/view/farmclub/component/farmclub_init.dart
  lib/view/farmclub/component/farmclub_make_edit.dart
  lib/view/farmclub/component/new_vegetable_item.dart
  lib/view/farmclub/component/new_vegetable_select.dart
  lib/view/farmclub/farmclub_challenge_screen.dart
  lib/view/farmclub/farmclub_detail_screen.dart
  lib/view/farmclub/farmclub_explore_screen.dart
  lib/view/farmclub/farmclub_help_screen.dart
  lib/view/farmclub/farmclub_mission_feed_screen.dart
  lib/view/farmclub/farmclub_register_screen.dart
  lib/view/farmclub/farmclub_search_screen.dart
  lib/view/home/component/register/register_screen.dart
  lib/view_model/controllers/crop/crop_help_controller.dart
  lib/view_model/controllers/crop/crop_info_step_controller.dart
  lib/view_model/controllers/farmclub/farmclub_detail_controller.dart
  lib/view_model/controllers/farmclub/farmclub_join_controller.dart
  lib/view_model/controllers/farmclub/farmclub_register_controller.dart
  lib/view_model/controllers/vege_controller.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#114 [feat] : 작물공간 삭제 및 팜히스토리 등록 페이지 완료 (#63)
  lib/view/home/component/result/custom_button.dart
  lib/view/home/component/result/home_final_apbar.dart
  lib/view/home/component/result/home_final_api_service.dart
  lib/view/home/component/result/home_final_controller.dart
  lib/view/home/component/result/home_final_dialog.dart
  lib/view/home/component/result/home_final_first.dart
  lib/view/home/component/result/home_final_progess_bar.dart
  lib/view/home/component/result/home_final_repository.dart
  lib/view/home/component/result/home_final_screen.dart
  lib/view/home/component/result/home_final_second.dart
  lib/view/home/component/result/home_final_third.dart
  lib/view/home/component/result/home_next_botton.dart
  lib/view/home/component/result/home_primary_botton.dart
  lib/view/home/component/result/home_select_box.dart
  lib/view/home/component/result/home_text_controller.dart
  lib/view/onboarding/onboarding_screen.dart
Labels: feat 👩🏻‍🌾, 건희 🍎
