Repository Mojacknong/Farmus_App, pull requests merged in 2023-10, with the labels that each got.

#3 [Feat] : 카카오 로그인, 구글 로그인 준비
  .vscode/settings.json
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  ios/firebase_app_id_file.json
  lib/firebase_options.dart
  lib/main.dart
  lib/view/login/loginScreen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/firebase_app_id_file.json
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat 👩🏻‍🌾, 아린 🌾

#6 Feature 5/logout
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/view/login/appInterceptor.dart
  lib/view/login/loginScreen.dart
  lib/view/logout/logoutScreen.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#7 [Feat] : 소셜 로그인 토큰을 서버 토큰으로 변경하고 재발급
  android/app/src/main/kotlin/com/example/mojacknong_android/MainActivity.kt
  lib/view/login/loginScreen.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat 👩🏻‍🌾, 아린 🌾

#9 [Feat] : 토큰 재발급 구현 및 파일 리팩토링
  lib/data/app_exceptions.dart
  lib/data/network/api_service.dart
  lib/data/network/base_api_services.dart
  lib/main.dart
  lib/model/data_model.dart
  lib/repository/home_repository.dart
  lib/res/app_url/app_url.dart
  lib/res/images/image_asset.dart
  lib/view/example/components/app_bar.dart
  lib/view/example/example_screen.dart
  lib/view/login/appInterceptor.dart
  lib/view/login/app_interceptor.dart
  lib/view/login/login_screen.dart
  lib/view/logout/logout_screen.dart
  lib/view_model/controllers/example_controller.dart
Labels: feat 👩🏻‍🌾, refactor 🥔, 아린 🌾

#11 [Refactor] : 로그인 부분 MVVM 패턴으로 리팩토링
  lib/data/app_exceptions.dart
  lib/data/network/api_service.dart
  lib/repository/home_repository.dart
  lib/repository/login_repository.dart
  lib/res/app_url/app_url.dart
  lib/view/login/login_screen.dart
  lib/view/logout/logout_screen.dart
  lib/view_model/login_model.dart
Labels: refactor 🥔, 아린 🌾
