Repository Mojacknong/Farmus_App, pull requests merged in 2024-08, with the labels that each got.

#219 [Feat] 날짜별 루틴 조회, 월별 루틴 조회, 루틴 추가
  ios/Podfile
  ios/Podfile.lock
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/farmus_calender.dart
  lib/common/form/digits_text_form_field.dart
  lib/data/network/base_api_services.dart
  lib/data/network/routine_service.dart
  lib/model/home/routine_model.dart
  lib/model/routine/my_veggie_routine_info_model.dart
  lib/model/routine/my_veggie_routine_info_model.freezed.dart
  lib/model/routine/my_veggie_routine_info_model.g.dart
  lib/model/routine/routine_date_list_model.dart
  lib/model/routine/routine_date_list_model.freezed.dart
  lib/model/routine/routine_date_list_model.g.dart
  lib/model/routine/routine_list_model.dart
  lib/model/routine/routine_month_list_model.dart
  lib/model/routine/routine_month_list_model.freezed.dart
  lib/model/routine/routine_month_list_model.g.dart
  lib/repository/routine_repository.dart
  lib/view/home/component/home_my_vege.dart
  lib/view/home/component/home_my_vege_list.dart
  lib/view/home/component/home_none_vege.dart
  lib/view/home/component/home_sub_title.dart
  lib/view/home/component/home_to_do.dart
  lib/view/home/component/home_vege_to_do.dart
  lib/view/home/component/my_vege_step.dart
  lib/view/home/component/none/home_my_vege_none.dart
  lib/view/home/component/vege_routine.dart
  lib/view/home/home_screen.dart
  lib/view/routine/component/routine_add.dart
  lib/view/routine/component/routine_bottom_sheet_content.dart
  lib/view/routine/routine_screen.dart
  lib/view/vege_info/vege_info_screen.dart
  lib/view_model/farmclub_open/farmclub_possible_vege.g.dart
  lib/view_model/home/home_provider.dart
  lib/view_model/home/notifier/to_do_notifier.dart
  lib/view_model/routine/notifier/routine_add_notifier.dart
  lib/view_model/routine/notifier/routine_add_notifier.g.dart
  lib/view_model/routine/notifier/routine_create_notifier.dart
  lib/view_model/routine/notifier/routine_date_list_notifier.dart
  lib/view_model/routine/notifier/routine_date_list_notifier.g.dart
  lib/view_model/routine/notifier/routine_edit_notifier.dart
  lib/view_model/routine/notifier/routine_list_notifier.dart
  lib/view_model/routine/notifier/routine_list_notifier.g.dart
  lib/view_model/routine/notifier/routine_month_list_notifier.dart
  lib/view_model/routine/notifier/routine_month_list_notifier.g.dart
  lib/view_model/routine/routine_provider.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#223 [Feat] 자동 로그인 추가
  lib/data/network/sign_in_api_service.dart
  lib/view/sign_in/sign_in_screen.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#225 [Feat] 루틴 체킹, 루틴 수정, 루틴 삭제
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/farmus_calender.dart
  lib/data/network/base_api_services.dart
  lib/data/network/routine_service.dart
  lib/model/home/routine_model.dart
  lib/repository/routine_repository.dart
  lib/view/home/component/home_vege_to_do.dart
  lib/view/home/component/vege_routine.dart
  lib/view/routine/component/routine_add.dart
  lib/view/routine/component/routine_bottom_sheet_content.dart
  lib/view/routine/routine_screen.dart
  lib/view_model/routine/notifier/routine_bottom_sheet_notifier.dart
  lib/view_model/routine/notifier/routine_bottom_sheet_notifier.g.dart
  lib/view_model/routine/notifier/routine_check_notifier.dart
  lib/view_model/routine/notifier/routine_check_notifier.g.dart
  lib/view_model/routine/notifier/routine_edit_notifier.dart
  lib/view_model/routine/routine_provider.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#226 [Feat] 프로필 정보 조회 API 연동
  lib/data/network/my_page_services.dart
  lib/model/my_page/my_page_info_model.dart
  lib/model/my_page/my_page_info_model.freezed.dart
  lib/model/my_page/my_page_info_model.g.dart
  lib/repository/my_page_repository.dart
  lib/view/my_page/component/my_page_info.dart
  lib/view/my_page/component/my_page_profile.dart
  lib/view/my_page/my_page_screen.dart
  lib/view/my_page/my_profile_screen.dart
  lib/view_model/my_page/my_page_info_provider.dart
  lib/view_model/my_page/my_page_info_provider.g.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#228 [Feat] 채소 삭제 API 연동
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/button/add_button.dart
  lib/common/button/delete_button.dart
  lib/common/button/primary_button.dart
  lib/data/network/my_veggie_service.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/my_vege/component/my_vege_list_info.dart
  lib/view/my_vege/component/veggie_delete_bottom_sheet_content.dart
  lib/view/my_vege/my_vege_screen.dart
  lib/view/vege_delete/vege_delete_screen.dart
  lib/view/vege_info/vege_info_screen.dart
  lib/view_model/my_vege/my_vege_provider.dart
  lib/view_model/my_vege/notifier/my_vege_delete_notifier.dart
  lib/view_model/my_vege/notifier/my_vege_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_delete_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_delete_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_info_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_info_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_list.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#231 [Feat] 일기 조회 API 수정
  assets/image/ic_heart_true.svg
  lib/common/button/round_gray_button.dart
  lib/common/farmus_picture.dart
  lib/common/farmus_picture_fix.dart
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/data/network/my_veggie_service.dart
  lib/model/diary/farmclub_open_diary_model.dart
  lib/model/diary/farmclub_open_diary_model.freezed.dart
  lib/model/diary/farmclub_open_diary_model.g.dart
  lib/model/diary/my_diary_add_model.dart
  lib/model/diary/my_veggie_diary.dart
  lib/model/diary/my_veggie_diary.freezed.dart
  lib/model/diary/my_veggie_diary.g.dart
  lib/model/diary/vege_diary_write_model.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/farmclub/component/farmclub_feed.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/component/feed_profile.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/home/component/home_diary.dart
  lib/view/home/component/home_farmclub_mission.dart
  lib/view/home/component/home_routine.dart
  lib/view/home/component/home_sub_title.dart
  lib/view/home/component/home_to_do_button.dart
  lib/view/home/component/home_vege_diary.dart
  lib/view/home/component/none/home_none_container.dart
  lib/view/home/home_screen.dart
  lib/view/mission_feed/component/mission_feed_tab_bar.dart
  lib/view/mission_feed_detail/component/feed_comment.dart
  lib/view/mission_feed_detail/mission_feed_detail_screen.dart
  lib/view/mission_write/component/mission_step_info.dart
  lib/view/mission_write/component/mission_write_route_button.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view/vege_diary/component/vege_diary_info.dart
  lib/view/vege_diary/component/vege_diary_widget.dart
  lib/view/vege_diary/vege_diary_screen.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_comment.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_content.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_icon.dart
  lib/view/vege_diary_detail/vege_diary_detail_screen.dart
  lib/view/vege_diary_write/vege_diary_write_screen.dart
  lib/view/vege_info/vege_info_screen.dart
  lib/view_model/diary/farmclub_open_diary_notifier.dart
  lib/view_model/diary/farmclub_open_diary_notifier.g.dart
  lib/view_model/diary/my_veggie_diary_notifier.dart
  lib/view_model/diary/my_veggie_diary_notifier.g.dart
  lib/view_model/home/notifier/veggie_diary_one_notifier.dart
  lib/view_model/home/notifier/veggie_diary_one_notifier.g.dart
  lib/view_model/my_page/my_page_info_provider.g.dart
  lib/view_model/my_vege/notifier/my_veggie_delete_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_delete_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_diary.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_notifier.g.dart
  lib/view_model/routine/notifier/routine_bottom_sheet_notifier.dart
  lib/view_model/routine/notifier/routine_bottom_sheet_notifier.g.dart
  lib/view_model/vege_diary_write/notifier/vege_diary_write_notifier.dart
  lib/view_model/vege_diary_write/vege_diary_write_provider.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#235 [Feat] 일기 댓글 조회 API 연동
  assets/image/ic_send.svg
  ios/Runner/AppDelegate.swift
  lib/common/bottom_sheet/diary_comment_bottom_sheet_content.dart
  lib/common/bottom_sheet/report_bottom_sheet.dart
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/content_empty.dart
  lib/common/form/comment_text_form_field.dart
  lib/common/form/primary_text_form_field.dart
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/data/network/my_veggie_service.dart
  lib/model/diary/diary_comment_add_model.dart
  lib/model/diary/diary_comment_model.dart
  lib/model/diary/diary_comment_model.freezed.dart
  lib/model/diary/diary_comment_model.g.dart
  lib/model/home/my_veggie_profile.dart
  lib/model/home/my_veggie_profile.freezed.dart
  lib/model/home/my_veggie_profile.g.dart
  lib/model/routine/routine_model.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/farmclub/component/farmclub_change_bottom_sheet_content.dart
  lib/view/farmclub/component/farmclub_feed.dart
  lib/view/farmclub/component/feed_profile.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/feed_detail/component/feed_comment.dart
  lib/view/feed_detail/feed_detail_screen.dart
  lib/view/home/component/home_my_vege.dart
  lib/view/mission_feed/component/mission_feed_tab_bar.dart
  lib/view/mission_feed_detail/component/feed_comment.dart
  lib/view/my_vege/component/my_vege_list_info.dart
  lib/view/my_vege/my_vege_screen.dart
  lib/view/vege_diary/component/vege_diary_widget.dart
  lib/view/vege_diary/vege_diary_screen.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_comment.dart
  lib/view/vege_diary_detail/vege_diary_detail_screen.dart
  lib/view/vege_info/vege_info_screen.dart
  lib/view_model/diary/diary_comment_add_notifier.dart
  lib/view_model/diary/diary_comment_add_notifier.g.dart
  lib/view_model/diary/diary_comment_delete_notifier.dart
  lib/view_model/diary/diary_comment_delete_notifier.g.dart
  lib/view_model/diary/diary_comment_notifier.dart
  lib/view_model/diary/diary_comment_notifier.g.dart
  lib/view_model/my_vege/notifier/my_vege_delete_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_delete_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_delete_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_info_mode_notifier.dart
  lib/view_model/routine/notifier/routine_bottom_sheet_notifier.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#238 [Feat] 팜클럽 히스토리 관련 모든 API 연동 완료
  android/gradle/wrapper/gradle-wrapper.properties
  lib/common/farmus_picture_fix.dart
  lib/data/network/my_history_service.dart
  lib/model/my_farmclub_history/farmclub_history_icon_model.dart
  lib/model/my_farmclub_history/farmclub_history_icon_model.freezed.dart
  lib/model/my_farmclub_history/farmclub_history_icon_model.g.dart
  lib/model/my_farmclub_history/my_farmclub_certification_model.dart
  lib/model/my_farmclub_history/my_farmclub_certification_model.freezed.dart
  lib/model/my_farmclub_history/my_farmclub_certification_model.g.dart
  lib/model/my_farmclub_history/my_farmclub_history_model.dart
  lib/model/my_farmclub_history/my_farmclub_history_model.freezed.dart
  lib/model/my_farmclub_history/my_farmclub_history_model.g.dart
  lib/model/my_farmclub_history/user_farmclub_history_model.dart
  lib/model/my_farmclub_history/user_farmclub_history_model.freezed.dart
  lib/model/my_farmclub_history/user_farmclub_history_model.g.dart
  lib/repository/my_history_repository.dart
  lib/view/my_certification/component/my_certification_feed.dart
  lib/view/my_certification/my_certification_screen.dart
  lib/view/my_farmclub/component/farmclub_history_list.dart
  lib/view/my_farmclub/component/farmclub_history_profile.dart
  lib/view/my_farmclub/component/farmclub_profile.dart
  lib/view/my_farmclub/component/farmclub_widget_pic.dart
  lib/view/my_farmclub/component/my_farmclub_stack_box.dart
  lib/view/my_page/component/my_history.dart
  lib/view/my_page/component/my_history_box.dart
  lib/view/my_page/component/my_vege_stack_box.dart
  lib/view/my_page/my_page_feed/my_page_feed.dart
  lib/view/my_page/my_page_feed/my_page_feed_picture.dart
  lib/view_model/my_farmclub_history/my_farmclub_certification_provider.dart
  lib/view_model/my_farmclub_history/my_farmclub_certification_provider.g.dart
  lib/view_model/my_farmclub_history/my_farmclub_history_notifier.dart
  lib/view_model/my_farmclub_history/my_farmclub_history_notifier.g.dart
  lib/view_model/my_page/my_history_farmclub_provider.dart
  lib/view_model/my_page/my_history_farmclub_provider.g.dart
  lib/view_model/my_page/my_page_farmclub_provider.dart
  lib/view_model/my_page/notifier/my_page_farmclub_count_notifier.dart
  lib/view_model/my_page/notifier/my_page_farmclub_info_notifier.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#240 [HotFix] 팜클럽 에러 관련 긴급 PR
  ios/Podfile.lock
  ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/data/network/base_api_services.dart
  lib/data/network/my_veggie_service.dart
  lib/model/diary/diary_comment_model.dart
  lib/model/diary/diary_comment_model.freezed.dart
  lib/model/diary/diary_comment_model.g.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/farmclub/component/farmclub_feed.dart
  lib/view/feed_detail/component/feed_comment.dart
  lib/view/feed_detail/feed_detail_screen.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_icon.dart
  lib/view/vege_diary_detail/vege_diary_detail_screen.dart
  lib/view_model/diary/diary_comment_delete_notifier.g.dart
  lib/view_model/diary/diary_comment_notifier.dart
  lib/view_model/diary/diary_comment_notifier.g.dart
  lib/view_model/diary/diary_like_notifier.dart
  lib/view_model/diary/diary_like_notifier.g.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, hotfix 🫐, 아린 🌾

#244 [Hotfix] 마이페이지 프로필 수정 & 히스토리
  lib/data/network/base_api_services.dart
  lib/data/network/farmclub_open_service.dart
  lib/data/network/my_history_service.dart
  lib/data/network/search_farmclub_service.dart
  lib/model/my_farmclub_history/farmclub_history_icon_model.dart
  lib/model/my_farmclub_history/farmclub_history_icon_model.freezed.dart
  lib/model/my_farmclub_history/farmclub_history_icon_model.g.dart
  lib/model/veggie_history/veggie_history_icon_model.dart
  lib/model/veggie_history/veggie_history_icon_model.freezed.dart
  lib/model/veggie_history/veggie_history_icon_model.g.dart
  lib/view/my_farmclub/component/my_farmclub_stack_box.dart
  lib/view/my_page/component/my_vege_stack_box.dart
  lib/view/search/component/search_farmclub_info.dart
  lib/view/search_farmclub/search_farmclub_screen.dart
  lib/view_model/diary/diary_like_notifier.g.dart
  lib/view_model/my_page/my_page_info_provider.dart
  lib/view_model/my_page/my_page_info_provider.g.dart
Labels: hotfix 🫐, 건희 🍎

#245 [Feat] 로그아웃, 토큰 재발급 구현
  lib/common/farmus_feed.dart
  lib/common/form/comment_text_form_field.dart
  lib/data/network/base_api_services.dart
  lib/data/network/on_boarding_service.dart
  lib/data/network/sign_in_api_service.dart
  lib/main.dart
  lib/repository/user_repository.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/feed_detail/component/diary_comment.dart
  lib/view/feed_detail/component/feed_detail_comment.dart
  lib/view/feed_detail/component/feed_detail_content.dart
  lib/view/feed_detail/component/feed_detail_icon.dart
  lib/view/feed_detail/feed_detail_screen.dart
  lib/view/my_setting/component/farmus_logout_bottom_sheet.dart
  lib/view/sign_in/app_interceptor.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view/vege_diary/component/vege_diary_widget.dart
  lib/view/vege_diary_detail/vege_diary_detail_screen.dart
  lib/view_model/my_page/notifier/logout_notifier.dart
  lib/view_model/my_page/notifier/logout_notifier.g.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#248 [Feat] 일기 추가, 삭제 API 연동
  lib/common/bottom_sheet/delete_bottom_sheet_content.dart
  lib/common/bottom_sheet/diary_comment_bottom_sheet_content.dart
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/button/diary_button.dart
  lib/common/button/primary_color_button.dart
  lib/common/image_picker/write_image_picker.dart
  lib/data/network/base_api_services.dart
  lib/data/network/my_page_services.dart
  lib/data/network/my_veggie_service.dart
  lib/data/network/on_boarding_service.dart
  lib/model/diary/diary_check_model.dart
  lib/model/diary/diary_check_model.freezed.dart
  lib/model/diary/diary_check_model.g.dart
  lib/model/diary/diary_comment_model.dart
  lib/model/diary/diary_comment_model.freezed.dart
  lib/model/diary/diary_comment_model.g.dart
  lib/model/home/diary_write_model.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/farmclub/component/feed_profile.dart
  lib/view/feed_detail/component/diary_comment.dart
  lib/view/feed_detail/feed_detail_screen.dart
  lib/view/home/component/home_diary.dart
  lib/view/mission_write/mission_write_screen.dart
  lib/view/vege_detail/vege_detail_screen.dart
  lib/view/vege_diary/vege_diary_screen.dart
  lib/view/vege_diary_write/component/vege_diary_write_bottom.dart
  lib/view/vege_diary_write/component/vege_diary_write_state.dart
  lib/view/vege_diary_write/vege_diary_write_screen.dart
  lib/view_model/diary/diary_check_notifier.dart
  lib/view_model/diary/diary_check_notifier.g.dart
  lib/view_model/diary/diary_delete_notifier.dart
  lib/view_model/diary/diary_delete_notifier.g.dart
  lib/view_model/diary/post_diary_notifier.dart
  lib/view_model/diary/post_diary_notifier.g.dart
  lib/view_model/home/home_provider.dart
  lib/view_model/home/notifier/toggle_switch_notifier.dart
  lib/view_model/routine/notifier/routine_cycle_switch_notifier.dart
  lib/view_model/routine/routine_provider.dart
  lib/view_model/vege_diary_write/notifier/post_diary_notifier.dart
  lib/view_model/vege_diary_write/notifier/vege_diary_write_notifier.dart
  lib/view_model/vege_diary_write/vege_diary_write_provider.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#252 [Feat] 팜클럽 미션 인증 API 연동 완료
  lib/data/network/my_farmclub_service.dart
  lib/data/network/my_page_services.dart
  lib/data/network/on_boarding_service.dart
  lib/model/mission/mission_write_model.dart
  lib/repository/my_farmclub_repository.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/mission_write/mission_write_screen.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view_model/mission_write/mission_write_provider.dart
  lib/view_model/mission_write/notifier/mission_write_notifier.dart
  lib/view_model/mission_write/notifier/post_mission_notifier.dart
  lib/view_model/mission_write/notifier/post_mission_notifier.g.dart
  lib/view_model/my_farmclub/farmclub_mission_certification_notifier.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#253 [Feat] 팜클럽 탈퇴 API 연동
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/data/network/my_farmclub_service.dart
  lib/repository/my_farmclub_repository.dart
  lib/view/farmclub/component/farmclub_exit_bottom_sheet_content.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/farmclub_open/farmclub_open_screen.dart
  lib/view_model/my_farmclub/my_farmclub_delete_notifier.dart
  lib/view_model/my_farmclub/my_farmclub_delete_notifier.g.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#255 [Hotfix] 머지 후 괄호 처리 오류 해결
  lib/data/network/my_farmclub_service.dart
  lib/repository/my_farmclub_repository.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/farmclub_success_screen.dart
  lib/view/mission_write/mission_write_screen.dart
  lib/view/my_farmclub/component/farmclub_history_profile.dart
  lib/view/my_farmclub/component/farmclub_widget_pic.dart
  lib/view/my_farmclub/component/my_farmclub_stack_box.dart
  lib/view/my_page/component/my_vege_stack_box.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view/veggie_history/component/veggie_history_profile.dart
  lib/view_model/mission_write/notifier/post_mission_notifier.dart
  lib/view_model/mission_write/notifier/post_mission_notifier.g.dart
  pubspec.lock
Labels: hotfix 🫐, refactor 🥔, 건희 🍎

#264 [Refactor] 팜클럽 미션 인증 & 탈퇴 리팩토링
  lib/model/my_farmclub/my_farmclub_info_model.dart
  lib/model/my_farmclub/my_farmclub_info_model.freezed.dart
  lib/model/my_farmclub/my_farmclub_info_model.g.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/mission_write/mission_write_screen.dart
  pubspec.lock
Labels: refactor 🥔, 건희 🍎

#268 [Feat] 홈파밍 히스토리 추가
  lib/data/network/my_veggie_service.dart
  lib/model/my_farmclub/mission_feed.dart
  lib/model/my_farmclub/mission_feed.freezed.dart
  lib/model/my_farmclub/mission_feed.g.dart
  lib/model/my_farmclub_history/veggie_delete_success_model.dart
  lib/model/my_vege/vege_delete_success_model.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/home/component/home_farmclub_mission.dart
  lib/view/mission_feed/component/mission_feed_tab_bar.dart
  lib/view/my_vege/component/veggie_delete_bottom_sheet_content.dart
  lib/view/vege_delete/component/vege_delete_fail.dart
  lib/view/vege_delete/component/vege_delete_success.dart
  lib/view/vege_delete/component/vege_success_image.dart
  lib/view/vege_delete/vege_delete_screen.dart
  lib/view_model/my_farmclub/mission_feed_notifier.g.dart
  lib/view_model/vege_delete/notifier/vege_delete_fail_notifier.dart
  lib/view_model/vege_delete/notifier/vege_delete_notifier.dart
  lib/view_model/vege_delete/notifier/vege_delete_success_notifier.dart
  lib/view_model/vege_delete/notifier/vege_delete_success_notifier.g.dart
  lib/view_model/vege_delete/vege_delete_provider.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#260 [Feat] 팜클럽 성공 화면 API 연동 완료
  assets/image/ic_mission_count.svg
  lib/common/two_info_box.dart
  lib/data/network/my_farmclub_service.dart
  lib/model/my_farmclub/farmclub_success_model.dart
  lib/model/my_farmclub/farmclub_success_model.freezed.dart
  lib/model/my_farmclub/farmclub_success_model.g.dart
  lib/repository/my_farmclub_repository.dart
  lib/view/farmclub/component/farmclub_success_info.dart
  lib/view/farmclub/farmclub_success_screen.dart
  lib/view/vege_diary/component/vege_diary_info.dart
  lib/view_model/my_farmclub/farmclub_success_info_notifier.dart
  lib/view_model/my_farmclub/farmclub_success_info_notifier.g.dart
Labels: feat 👩🏻‍🌾, 건희 🍎
