Repository Mojacknong/Farmus_App, pull requests merged in 2024-05, with the labels that each got.

#153 [Feat] 탐색 탭의 첫 페이지 UI 구현
  assets/image/ic_search_glass.svg
  assets/image/ic_xmark_blue.svg
  assets/image/ic_xmark_orange.svg
  assets/image/ic_xmark_red.svg
  lib/common/theme/farmus_theme_color.dart
  lib/view/main/main_screen.dart
  lib/view/my_page/component/my_page_app_bar.dart
  lib/view/my_page/my_page_screen.dart
  lib/view/search/component/search_difficulty_box.dart
  lib/view/search/component/search_difficulty_btn.dart
  lib/view/search/component/search_farmclub_info.dart
  lib/view/search/component/search_farmclub_info_widget.dart
  lib/view/search/component/search_tab_bar.dart
  lib/view/search/component/search_vege_info.dart
  lib/view/search/component/search_welcome_text.dart
  lib/view/search/search_screen.dart
  lib/view_model/search/notifier/search_difficulty_notifier.dart
  lib/view_model/search/search_provider.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#159 [Feat] 팜클럽 초기 UI 구현
  assets/image/ic_farmclub.svg
  assets/image/ic_farmclub_mark.svg
  assets/image/image_farmclub_profile_background.png
  lib/common/base/base_tab_bar.dart
  lib/common/farmus_picture_fix.dart
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/common/tab_bar/primary_tab_bar.dart
  lib/common/theme/farmus_theme_color.dart
  lib/common/theme/farmus_theme_text_style.dart
  lib/view/farmclub/component/diary_profile.dart
  lib/view/farmclub/component/farmclub_open_diary.dart
  lib/view/farmclub/component/farmclub_profile.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/component/farmclub_step_tip.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/home/component/home_my_vege.dart
  lib/view/home/component/home_vege_diary.dart
  lib/view/home/component/home_vege_routine.dart
  lib/view/home/component/home_vege_to_do.dart
  lib/view/home/component/vege_routine.dart
  lib/view/home/home_screen.dart
  lib/view/main/main_screen.dart
  lib/view/my_farmclub/component/my_farmclub_stack_box.dart
  lib/view/vege_diary/component/vege_diary_widget.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_comment.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_content.dart
  lib/view/vege_diary_detail/vege_diary_detail_screen.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#158 [Feat] 탐색 탭의 "팝클럽이란" UI 구현
  assets/image/img_about_farmclub_first.png
  assets/image/img_about_farmclub_fourth_step1.png
  assets/image/img_about_farmclub_fourth_step2.png
  assets/image/img_about_farmclub_fourth_step6.png
  assets/image/img_about_farmclub_plus.png
  assets/image/img_about_farmclub_second_step3.png
  assets/image/img_about_farmclub_second_tip.png
  assets/image/img_about_farmclub_third.png
  lib/common/theme/farmus_theme_color.dart
  lib/common/theme/farmus_theme_text_style.dart
  lib/view/search/component/about_farmclub/about_farmclub_first.dart
  lib/view/search/component/about_farmclub/about_farmclub_fourth.dart
  lib/view/search/component/about_farmclub/about_farmclub_second.dart
  lib/view/search/component/about_farmclub/about_farmclub_third.dart
  lib/view/search/component/about_farmclub/about_farmclub_widget.dart
  lib/view/search/search_screen.dart
  lib/view/search_farmclub/search_farmclub_screen.dart
  lib/view_model/search/notifier/page_notifier.dart
  lib/view_model/search/search_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 건희 🍎

#161 [Refactor] PrimaryTabBar 수정 및 적용
  lib/common/base/base_tab_bar.dart
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/common/tab_bar/primary_tab_bar.dart
  lib/view/my_farmclub/component/my_farmclub_stack_box.dart
  lib/view/my_page/component/my_history_box.dart
  lib/view/my_page/component/my_vege_stack_box.dart
  lib/view/my_page/my_page_screen.dart
  lib/view/search/component/search_tab_bar.dart
  lib/view/search/component/search_vege_info.dart
  lib/view/search/search_screen.dart
  lib/view/vege_history/component/vege_history_tap_bar.dart
Labels: refactor 🥔, 건희 🍎

#170 [Feat] 미션 인증하기 UI 구현
  ios/Podfile.lock
  lib/common/app_bar/delete_app_bar.dart
  lib/common/button/primary_color_button.dart
  lib/common/form/content_input_text_form.dart
  lib/common/image_picker/write_image_picker.dart
  lib/common/tab_bar/primary_tab_bar.dart
  lib/common/theme/farmus_theme_text_style.dart
  lib/model/mission/mission_write_model.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/component/farmclub_step_tip.dart
  lib/view/mission_feed/mission_feed_screen.dart
  lib/view/mission_write/component/mission_step_info.dart
  lib/view/mission_write/mission_write_screen.dart
  lib/view/tip/component/tip_expand_card.dart
  lib/view/tip/component/tip_step_text.dart
  lib/view/tip/tip_screen.dart
  lib/view/vege_delete/component/vege_delete_success.dart
  lib/view/vege_delete/vege_delete_screen.dart
  lib/view/vege_diary_write/vege_diary_write_screen.dart
  lib/view_model/mission_write/mission_write_provider.dart
  lib/view_model/mission_write/notifier/mission_write_notifier.dart
  lib/view_model/vege_diary_write/notifier/vege_diary_write_notifier.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#171 [Feat] 미션 피드 UI 구현
  lib/common/theme/farmus_theme_text_style.dart
  lib/view/farmclub/component/farmclub_feed.dart
  lib/view/farmclub/component/farmclub_open_diary.dart
  lib/view/farmclub/component/farmclub_profile.dart
  lib/view/farmclub/component/farmclub_select_profile.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/component/feed_profile.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/mission_feed/component/farmclub_basic_profile.dart
  lib/view/mission_feed/component/mission_feed_basic_profile.dart
  lib/view/mission_feed/component/mission_feed_profile.dart
  lib/view/mission_feed/component/mission_feed_select_profile.dart
  lib/view/mission_feed/component/mission_feed_tab_bar.dart
  lib/view/mission_feed/mission_feed_screen.dart
  lib/view/mission_feed_detail/component/feed_comment.dart
  lib/view/mission_feed_detail/mission_feed_detail_screen.dart
  lib/view/mission_write/component/mission_step_info.dart
  lib/view/mission_write/component/mission_write_route_button.dart
  lib/view/mission_write/mission_write_screen.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_comment.dart
  lib/view/vege_diary_detail/component/vege_diary_detail_content.dart
  lib/view/vege_diary_detail/vege_diary_detail_screen.dart
  lib/view/vege_info/vege_info_screen.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#175 [Refactor] 팜클럽 준비사항 리팩토링
  lib/view/farmclub_sign_up/component/farmclub_ preparations.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_button.dart
  lib/view/farmclub_sign_up/farmclub_sign_up_screen.dart
Labels: refactor 🥔, 건희 🍎

#177 [Feat] 마이페이지의 설정페이지 UI 구현
  lib/common/bottom_sheet/primary_action_sheet.dart
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_button.dart
  lib/view/my_page/my_page_screen.dart
  lib/view/my_setting/component/my_setting_text.dart
  lib/view/my_setting/component/my_setting_web.dart
  lib/view/my_setting/my_setting_screen.dart
  lib/view_model/my_setting/my_setting_provider.dart
  lib/view_model/my_setting/notifier/my_setting_push_alarm_switch_notifier.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 건희 🍎

#180 [Feat] 팜클럽 바텀시트, Empty 컴포넌트 구현
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/button/select_box_basic_content.dart
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/view/farmclub/component/farmclub_change_bottom_sheet_content.dart
  lib/view/farmclub/component/farmclub_change_info.dart
  lib/view/farmclub/component/farmclub_empty.dart
  lib/view/farmclub/component/farmclub_exit_bottom_sheet_content.dart
  lib/view/farmclub/component/farmclub_profile.dart
  lib/view/farmclub/component/farmclub_step_empty.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/my_farmclub/component/farmclub_profile.dart
  lib/view/vege_delete/component/vege_delete_fail.dart
Labels: feat 👩🏻‍🌾, 아린 🌾
