Repository Mojacknong/Farmus_App, pull requests merged in 2024-06, with the labels that each got.

#182 [Feat] 로그인 API 연동
  ios/Podfile
  ios/Podfile.lock
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/data/network/base_api_services.dart
  lib/data/network/login_api_service.dart
  lib/data/network/on_boarding_service.dart
  lib/data/network/sign_in_api_service.dart
  lib/main.dart
  lib/repository/login_repository.dart
  lib/repository/on_boarding_repository.dart
  lib/repository/sign_in_repository.dart
  lib/res/app_url/app_url.dart
  lib/view/on_boarding/on_boarding_finish_screen.dart
  lib/view/on_boarding/on_boarding_screen.dart
  lib/view/sign_in/app_interceptor.dart
  lib/view/sign_in/component/sign_in_img_widget.dart
  lib/view/sign_in/sign_in_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 아린 🌾

#186 [Feat] 온보딩 API 연동
  analysis_options.yaml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/common/button/white_color_button.dart
  lib/data/network/base_api_services.dart
  lib/data/network/on_boarding_service.dart
  lib/data/network/sign_in_api_service.dart
  lib/model/on_boarding/on_boarding_level_model.dart
  lib/model/on_boarding/on_boarding_motivation_model.dart
  lib/model/on_boarding/on_boarding_time_model.dart
  lib/model/on_boarding/on_boarding_user_profile_model.dart
  lib/repository/on_boarding_repository.dart
  lib/repository/sign_in_repository.dart
  lib/repository/user_repository.dart
  lib/view/my_page/component/my_page_profile.dart
  lib/view/my_page/my_profile_screen.dart
  lib/view/on_boarding/component/on_boarding_first.dart
  lib/view/on_boarding/component/on_boarding_fourth.dart
  lib/view/on_boarding/component/on_boarding_nickname_text_input.dart
  lib/view/on_boarding/component/on_boarding_second.dart
  lib/view/on_boarding/component/on_boarding_third.dart
  lib/view/on_boarding/on_boarding_finish_screen.dart
  lib/view/on_boarding/on_boarding_screen.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view_model/on_boarding/move_notifier.dart
  lib/view_model/on_boarding/notifier/level_notifier.dart
  lib/view_model/on_boarding/notifier/motivation_notifier.dart
  lib/view_model/on_boarding/notifier/time_notifier.dart
  lib/view_model/on_boarding/on_boarding_finish_notifier.dart
  lib/view_model/on_boarding/on_boarding_finish_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_level_notifier.dart
  lib/view_model/on_boarding/on_boarding_level_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_motivation_notifier.dart
  lib/view_model/on_boarding/on_boarding_motivation_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_provider.dart
  lib/view_model/on_boarding/on_boarding_provider.g.dart
  lib/view_model/on_boarding/on_boarding_user_profile.dart
  lib/view_model/on_boarding/on_boarding_user_profile.g.dart
  lib/view_model/on_boarding/profile_notifier.dart
  lib/view_model/on_boarding/special_character_notifier.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 아린 🌾

#189 [Feat] 초기 화면 API 연동
  lib/data/network/my_veggie_service.dart
  lib/model/home/recommend_veggie_model.dart
  lib/model/home/recommend_veggie_model.freezed.dart
  lib/model/home/recommend_veggie_model.g.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/home/component/home_none_vege.dart
  lib/view/home/component/home_vege_to_do.dart
  lib/view/home/component/none/home_my_vege_none.dart
  lib/view/home/component/none/home_none_container.dart
  lib/view/home/component/none/home_vege_info.dart
  lib/view/home/home_screen.dart
  lib/view/vege_add/component/home_vege_add_first.dart
  lib/view_model/home/recommend_veggie_info_notifier.dart
  lib/view_model/home/recommend_veggie_info_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_list_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_list_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_finish_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_level_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_motivation_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_user_profile.g.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#193 [Feat] 팜클럽 검색 탭 API 연동
  lib/data/network/search_farmclub_service.dart
  lib/repository/search_farmclub_repository.dart
  lib/view/search_farmclub/component/search_farmclub_backgroud.dart
  lib/view/search_farmclub/component/search_farmclub_result.dart
  lib/view/search_farmclub/search_farmclub_screen.dart
  lib/view_model/search_farmclub/search_farmclub_provider.dart
  lib/view_model/search_farmclub/search_farmclub_provider.g.dart
Labels: feat 👩🏻‍🌾, 건희 🍎

#197 [Feat] 홈 화면 채소 정보, 일기 조회
  lib/common/button/primary_button.dart
  lib/data/network/my_veggie_service.dart
  lib/model/home/my_veggie_list_model.dart
  lib/model/home/my_veggie_list_model.freezed.dart
  lib/model/home/my_veggie_list_model.g.dart
  lib/model/home/my_veggie_profile.dart
  lib/model/home/my_veggie_profile.freezed.dart
  lib/model/home/my_veggie_profile.g.dart
  lib/model/home/veggie_diary_model.dart
  lib/model/home/veggie_diary_model.freezed.dart
  lib/model/home/veggie_diary_model.g.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/home/component/home_my_vege.dart
  lib/view/home/component/home_my_vege_list.dart
  lib/view/home/component/home_vege_diary.dart
  lib/view/home/home_screen.dart
  lib/view/vege_add/home_vege_add_screen.dart
  lib/view_model/home/home_provider.dart
  lib/view_model/home/notifier/my_veggie_add_notifier.g.dart
  lib/view_model/home/notifier/veggie_diary_one_notifier.dart
  lib/view_model/home/notifier/veggie_diary_one_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_list.dart
  lib/view_model/my_vege/notifier/my_veggie_list.g.dart
  lib/view_model/my_vege/notifier/my_veggie_list_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_notifier.g.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#199 [Feat] 내 채소 선택 및 팜클럽 가입 API 연동
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/data/network/search_farmclub_service.dart
  lib/model/farmclub_sign_up/farmclub_sign_up_model.dart
  lib/model/farmclub_sign_up/farmclub_sign_up_model.freezed.dart
  lib/model/farmclub_sign_up/farmclub_sign_up_model.g.dart
  lib/model/farmclub_sign_up/farmclub_sign_up_vege_model.dart
  lib/model/search/search_farmclub_detail_model.dart
  lib/model/search/search_farmclub_detail_model.freezed.dart
  lib/model/search/search_farmclub_detail_model.g.dart
  lib/repository/search_farmclub_repository.dart
  lib/view/farmclub_open/farmclub_open_screen.dart
  lib/view/farmclub_sign_up/component/farmclub_bottom_sheet_subtitle.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_bottom_sheet_content.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_button.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_vege_toggle_widget.dart
  lib/view/farmclub_sign_up/farmclub_sign_up_screen.dart
  lib/view/my_setting/my_setting_screen.dart
  lib/view_model/farmclub_sign_up/farmclub_info_provider.dart
  lib/view_model/farmclub_sign_up/farmclub_info_provider.g.dart
  lib/view_model/farmclub_sign_up/farmclub_sign_up_final_provider.dart
  lib/view_model/farmclub_sign_up/farmclub_sign_up_final_provider.g.dart
  lib/view_model/farmclub_sign_up/farmclub_sign_up_vege_select_provider.dart
  lib/view_model/farmclub_sign_up/farmclub_sign_veggie_provider.dart
  lib/view_model/farmclub_sign_up/farmclub_sign_veggie_provider.g.dart
  lib/view_model/farmclub_sign_up/notifier/farmclub_sign_up_vege_select_notifier.dart
  lib/view_model/farmclub_sign_up/notifier/toggle_notifier.dart
  lib/view_model/farmclub_sign_up/toggle_notifier_provider.dart
Labels: feat 👩🏻‍🌾, refactor 🥔, 건희 🍎

#202 [Feat] 팜클럽 연동
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/data/network/my_farmclub_service.dart
  lib/data/network/my_veggie_service.dart
  lib/model/my_farmclub/my_farmclub_info_model.dart
  lib/model/my_farmclub/my_farmclub_info_model.freezed.dart
  lib/model/my_farmclub/my_farmclub_info_model.g.dart
  lib/model/my_farmclub/my_farmclub_model.dart
  lib/model/my_farmclub/my_farmclub_model.freezed.dart
  lib/model/my_farmclub/my_farmclub_model.g.dart
  lib/repository/my_farmclub_repository.dart
  lib/repository/my_veggie_garden_repository.dart
  lib/view/farmclub/component/farmclub_empty.dart
  lib/view/farmclub/component/farmclub_feed.dart
  lib/view/farmclub/component/farmclub_profile.dart
  lib/view/farmclub/component/farmclub_select_profile.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/component/farmclub_step_tip.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/home/component/home_vege_to_do.dart
  lib/view/home/home_screen.dart
  lib/view/mission_feed/component/mission_feed_profile.dart
  lib/view/mission_feed/component/mission_feed_select_profile.dart
  lib/view/mission_feed/component/mission_feed_tab_bar.dart
  lib/view/my_farmclub/component/farmclub_profile.dart
  lib/view/vege_diary/component/vege_diary_info.dart
  lib/view/vege_diary/vege_diary_screen.dart
  lib/view_model/my_farmclub/my_farmclub_info_notifier.dart
  lib/view_model/my_farmclub/my_farmclub_info_notifier.g.dart
  lib/view_model/my_farmclub/my_farmclub_notifier.dart
  lib/view_model/my_farmclub/my_farmclub_notifier.g.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_notifier.g.dart
Labels: feat 👩🏻‍🌾, 아린 🌾
