Repository Mojacknong/Farmus_App, pull requests merged in 2024-07, with the labels that each got.

#207 [Feat] 다른 팜클럽 조회
  ios/Podfile
  ios/Podfile.lock
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/view/farmclub/component/farmclub_change_bottom_sheet_content.dart
  lib/view/farmclub/component/farmclub_change_info.dart
  lib/view/farmclub/component/farmclub_profile.dart
  lib/view/farmclub/component/farmclub_select_profile.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/mission_feed/component/mission_feed_profile.dart
  lib/view/mission_feed/component/mission_feed_select_profile.dart
  lib/view/my_farmclub/component/farmclub_profile.dart
  lib/view/sign_in/sign_in_screen.dart
  lib/view_model/farmclub_sign_up/farmclub_sign_up_final_provider.g.dart
  lib/view_model/home/home_provider.dart
  lib/view_model/my_farmclub/my_farmclub_info_notifier.dart
  lib/view_model/my_farmclub/my_farmclub_info_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_finish_notifier.g.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 아린 🌾

#210 [Feat] 팜클럽 미션 조회 API 연동
  lib/common/app_bar/home_app_bar.dart
  lib/common/button/home_my_vege_button.dart
  lib/common/tab_bar/farmclub_tab_bar.dart
  lib/data/network/my_farmclub_service.dart
  lib/model/my_farmclub/farmclub_help_model.dart
  lib/model/my_farmclub/farmclub_help_model.freezed.dart
  lib/model/my_farmclub/farmclub_help_model.g.dart
  lib/repository/my_farmclub_repository.dart
  lib/view/farmclub/component/farmclub_change_info.dart
  lib/view/farmclub/component/farmclub_profile.dart
  lib/view/farmclub/component/farmclub_step.dart
  lib/view/farmclub/farmclub_screen.dart
  lib/view/home/component/home_my_vege_list.dart
  lib/view/home/home_screen.dart
  lib/view/mission_feed/component/mission_feed_select_profile.dart
  lib/view/mission_feed/component/mission_feed_tab_bar.dart
  lib/view/mission_feed/mission_feed_screen.dart
  lib/view/mission_write/component/mission_step_info.dart
  lib/view/mission_write/component/mission_write_route_button.dart
  lib/view/mission_write/mission_write_screen.dart
  lib/view/my_farmclub/component/farmclub_profile.dart
  lib/view/on_boarding/on_boarding_finish_screen.dart
  lib/view/tip/component/tip_expand_card.dart
  lib/view/tip/component/tip_step_text.dart
  lib/view/tip/tip_screen.dart
  lib/view/vege_diary/vege_diary_screen.dart
  lib/view/vege_diary_write/component/vege_diary_write_state.dart
  lib/view/vege_diary_write/vege_diary_write_screen.dart
  lib/view_model/home/home_provider.dart
  lib/view_model/my_farmclub/farmclub_help_notifier.dart
  lib/view_model/my_farmclub/farmclub_help_notifier.g.dart
  lib/view_model/my_farmclub/farmclub_mission_certification_notifier.dart
  lib/view_model/my_farmclub/farmclub_mission_certification_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_finish_notifier.dart
  pubspec.lock
Labels: feat 👩🏻‍🌾, 아린 🌾

#212 [Feat] 내 채소 정보 API 연동
  lib/common/button/primary_color_button.dart
  lib/common/button/white_color_button.dart
  lib/common/farmus_calender.dart
  lib/common/form/primary_text_form_field.dart
  lib/data/network/base_api_services.dart
  lib/data/network/veggie_info_service.dart
  lib/model/my_vege/my_veggie_info.dart
  lib/model/my_vege/my_veggie_info_model.dart
  lib/model/my_vege/my_veggie_info_model.freezed.dart
  lib/model/my_vege/my_veggie_info_model.g.dart
  lib/repository/user_repository.dart
  lib/repository/veggie_info_repository.dart
  lib/view/home/component/home_my_vege.dart
  lib/view/home/home_screen.dart
  lib/view/my_vege/component/my_vege_list_info.dart
  lib/view/vege_add/component/home_vege_add_first.dart
  lib/view/vege_add/component/home_vege_name_input.dart
  lib/view/vege_info/component/vege_info_detail.dart
  lib/view/vege_info/vege_info_screen.dart
  lib/view_model/home/notifier/my_veggie_add_notifier.dart
  lib/view_model/home/notifier/my_veggie_add_notifier.g.dart
  lib/view_model/my_farmclub/farmclub_mission_certification_notifier.g.dart
  lib/view_model/my_vege/my_vege_provider.dart
  lib/view_model/my_vege/notifier/my_vege_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_info.dart
  lib/view_model/my_vege/notifier/my_veggie_info.g.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_change_notifier.dart
  lib/view_model/my_vege/notifier/my_veggie_profile_change_notifier.g.dart
  lib/view_model/on_boarding/on_boarding_finish_notifier.g.dart
Labels: feat 👩🏻‍🌾, 아린 🌾

#209 [Refactor] 팜클럽 가입하기 데이터 최신화 및 화면 이동
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_bottom_sheet_content.dart
  lib/view/farmclub_sign_up/component/farmclub_sign_up_button.dart
  lib/view/farmclub_sign_up/farmclub_sign_up_screen.dart
Labels: refactor 🥔, 건희 🍎

#216 [Feat] 팜클럽 생성 API연동
  android/build.gradle
  lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
  lib/common/farmus_calender.dart
  lib/common/form/digits_text_form_field.dart
  lib/data/network/farmclub_open_service.dart
  lib/model/farmclub_open/farmclub_my_vege_model.dart
  lib/model/farmclub_open/farmclub_my_vege_model.freezed.dart
  lib/model/farmclub_open/farmclub_my_vege_model.g.dart
  lib/model/farmclub_open/farmclub_possible_model.dart
  lib/model/farmclub_open/farmclub_possible_model.freezed.dart
  lib/model/farmclub_open/farmclub_possible_model.g.dart
  lib/model/farmclub_open/farmclub_vege_list_model.dart
  lib/model/farmclub_open/farmclub_vege_list_model.freezed.dart
  lib/model/farmclub_open/farmclub_vege_list_model.g.dart
  lib/repository/farmclub_open_repository.dart
  lib/view/farmclub_open/component/farmclub_intro_input.dart
  lib/view/farmclub_open/component/farmclub_name_input.dart
  lib/view/farmclub_open/component/farmclub_num_input.dart
  lib/view/farmclub_open/component/farmclub_open_bottom_sheet_content.dart
  lib/view/farmclub_open/component/farmclub_open_calendar.dart
  lib/view/farmclub_open/component/farmclub_vege_list.dart
  lib/view/farmclub_open/farmclub_open_screen.dart
  lib/view/my_setting/component/farmclub_quit_bottom_sheet_content.dart
  lib/view/my_setting/component/farmus_logout_bottom_sheet.dart
  lib/view/search/search_screen.dart
  lib/view_model/farmclub_open/farmclub_my_vege_provider.dart
  lib/view_model/farmclub_open/farmclub_my_vege_provider.g.dart
  lib/view_model/farmclub_open/farmclub_open_provider.dart
  lib/view_model/farmclub_open/farmclub_possible_vege.dart
  lib/view_model/farmclub_open/farmclub_possible_vege.g.dart
  lib/view_model/farmclub_open/notifier/farmclub_open_info_notifier.dart
  lib/view_model/farmclub_open/notifier/farmclub_open_info_notifier.g.dart
  pubspec.lock
  pubspec.yaml
Labels: feat 👩🏻‍🌾, 건희 🍎
